wrapperVersion=3.3.4
distributionType=only-script
# Maven 3.9.X
distributionUrl=https://mirrors.huaweicloud.com/apache/maven/maven-3/3.9.12/binaries/apache-maven-3.9.12-bin.zip
# Maven 4.0
#distributionUrl=https://mirrors.huaweicloud.com/apache/maven/maven-4/4.0.0-rc-5/binaries/apache-maven-4.0.0-rc-5-bin.zip
# 分发类型为 only-script 或 bin 可以不需要该项（因为用不到），具体参考：https://maven.apache.org/tools/wrapper/maven-wrapper-distribution/index.html
#wrapperUrl=https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.3.4/maven-wrapper-3.3.4.jar
