<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ruoyi-vue-plus</artifactId>
        <groupId>org.dromara</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>ruoyi-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        ruoyi-modules 业务模块
    </description>

    <modules>
        <!-- demo模块 -->
        <module>ruoyi-demo</module>
        <!-- 代码生成模块 -->
        <module>ruoyi-gen</module>
        <!-- 调度任务模块 -->
        <module>ruoyi-job</module>
        <!-- 系统模块 -->
        <module>ruoyi-system</module>
        <!-- 工作流模块 -->
        <module>ruoyi-workflow</module>
        <!-- AI业务模块 -->
        <module>ruoyi-ai</module>
    </modules>

</project>
