<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ruoyi-vue-plus</artifactId>
        <groupId>org.dromara</groupId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>ruoyi-extend</artifactId>
    <packaging>pom</packaging>

    <modules>
        <!-- 监控服务 -->
        <module>ruoyi-monitor-admin</module>
        <!-- Snail AI 服务端 -->
        <module>ruoyi-snailai-server</module>
        <!-- SnailJob 服务端 -->
        <module>ruoyi-snailjob-server</module>
    </modules>

</project>
